# encoding=utf-8

# 测试环境
befinx_base_url = "http://192.168.6.42/"
host = "192.168.6.230"  # 测试服
# host = '192.168.6.150'
# host = "192.168.6.44"  # 无界通测试服
ip = "{}:8001".format(host)
# RedisHost = "127.0.0.1"   # 测试服务器需用127.0.0.1
RedisHost = "192.168.6.230"
RedisPassword = "Shop123456_"
# MysqlHost = "127.0.0.1" # 测试服务器需用127.0.0.1
MysqlHost = "192.168.6.230"
MysqlPassword = 'c78af2758c044bdf'
MysqlDatabase = "py_orderlist"
MysqlDatabase_grid_password = "ywHChF4zJ3JZfDcs"
MysqlDatabase_grid = "t_better_bourse_im"

# 正式环境APP版
# import requests
# befinx_base_url = "https://www.befinx.com"
# host = "47.244.174.13"  # java端接口
# ip = "{}:8001".format(host)
# RedisHost = "47.244.174.13"
# RedisPassword = "qzWtmc4RyzPQKLsC"
# MysqlHost = "47.244.174.13"
# MysqlPassword = 'EtCjrtTAAWAW6HfL'
# MysqlDatabase = "py_orderlist"
# MysqlDatabase_grid_password = "ywHChF4zJ3JZfDcs"
# MysqlDatabase_grid = "t_better_bourse"

# 正式环境无界通版url
# befinx_base_url = "https://www.befinx.com"
# host = "172.31.65.20"  # java端接口服务器内网，本地调用下方接口
# # host = "47.57.72.251"  # java端接口
# ip = "{}:8001".format(host)
# # RedisHost = "127.0.0.1"
# RedisHost = "47.56.242.24"
# RedisPassword = "H7eY4M1Px8KOZ9VT"
# # MysqlHost = "127.0.0.1"
# MysqlHost = "47.56.242.24"
# MysqlPassword = '38xhm$0apYO$xcYr'
# MysqlDatabase = "py_strategy_orderlist"
# MysqlDatabase_grid = "t_better_bourse_im"

# 交易所可用api(本地)
huobi_api_url = "api.huobi.pr"
okex_api_url = "www.okexcn.com"
binance_api_url = "www.binancezh.pro"

# 交易所可用api(服务器)
# huobi_api_url = "api.huobi.pro"
# okex_api_url = "www.okex.com"
# binance_api_url = "www.binancezh.com"

#  委托交易接口
Trade_url = "http://{}/api/v1/bourse/python/python_call/create".format(ip)
# 撤单接口
Cancel_url = "http://{}/api/v1/bourse/python/python_call/updateOrder".format(ip)
# 查询订单接口
Queryorder_url = "http://{}/api/v1/bourse/python/python_call/selectOrderByOrderId".format(ip)
# 查询订单实际成交价（比如8000买单，实际成交价7999）
Query_tradeprice_url = "http://{}/api/v1/bourse/python/python_call/getByTransactionHistory".format(ip)
# 查询单个平台资产（参数?platform,userId）
Remain_url = "http://{}/api/v1/bourse/python/python_call/selectAssetsByAccountId".format(ip)
# 修改补仓策略的买单均价,状态
updateCover_url = 'http://{}/api/v1/bourse/python/cover_strategy/pythonUpdateCover'.format(ip)
# 修改跟单的状态
updateCopy_url = 'http://{}/api/v1/bourse/python/cover_strategy/pythonUpdateCopy'.format(ip)
# 修改网格策略状态
updateGridStatus = "http://{}/api/v1/bourse/python/python_call/updateGridStrategyStatus".format(ip)
# 修改长线追踪策略接口（修改状态返回收益等）
updateTraceStrategy = "http://{}/api/v1/bourse/python/python_call/updateTraceStrategy".format(ip)
# 短信发送接口
sendmessage_url = "http://{}/api/v1/bourse/python/python_call/doSmsStrategyStop".format(ip)
# 组合策略（量化3）1:运行中 2:已完成 3:已手动停止 4:防错停止 5:长线完成 6: 止损停止
stopStrategy3_url = "http://{}/api/v1/bourse/python/python_call/updateCombinationStatus".format(ip)
# 组合策略第一步长线完成，开启网格的接口
updateStrategy3_url = "http://{}/api/v1/bourse/python/python_call/updateCombinationStrategy".format(ip)
# 平衡策略停止 3止损停止，4异常停止
stopBalanceStrategy_url = "http://{}/api/v1/bourse/python/python_call/updateBalancStrategyStatus".format(ip)
# 大数据计算修改网格间距
updatgridspacing_url = "http://{}/api/v1/bourse/python/python_call/updateGridSpacingByNmae".format(ip)
# 做市策略已完成（停止）
stopMarketMarketStrategy_url = "http://{}/api/v1/bourse/python/python_call/stopMarketMarketStrategy".format(ip)
# 合约下单接口（根据对手价）
futures_trade_url = "http://{}/api/v1/bourse/python/python_contract/addContractOrder".format(ip)
# 合约挂单接口（止盈止损）
futures_order_url = "http://{}/api/v1/bourse/python/python_contract/addContractTriggerOrder".format(ip)
# 合约撤单接口
futures_cancel_order_url = "http://{}/api/v1/bourse/python/python_contract/contractTriggerCancel".format(ip)

# 对冲同步订单到java
hedge_syncOrder_url = "http://{}/api/v1/bourse/python/hedge_strategy/syncOrder".format(ip)
# 对冲下单
hedge_place_order = "http://{}/api/v1/bourse/python/hedge_strategy/create".format(ip)
# 对冲查询
hedge_query_order = "http://{}/api/v1/bourse/python/hedge_strategy/findByOrderId".format(ip)
# 对冲撤单
hedge_cancel_order = "http://{}/api/v1/bourse/python/hedge_strategy/cancel".format(ip)

# 费率
Fee = {"bitz": {"sellfee": 0.0008, "buyfee": 0.0008},
       "okex": {"sellfee": 0.001, "buyfee": 0.001},
       "bw": {"sellfee": 0.002, "buyfee": 0.002},
       "binance": {"sellfee": 0.001, "buyfee": 0.001},
       "zb": {"sellfee": 0.002, "buyfee": 0.002},
       "gate": {"sellfee": 0.002, "buyfee": 0.002},
       "huobi": {"sellfee": 0.002, "buyfee": 0.002},
       "befinx": {"sellfee": 0.002, "buyfee": 0.002},
       }

# 网格间距
gapdict = {"btc_usdt": 400,
           "eth_usdt": 10,
           "eos_usdt": 0.04,
           "xrp_usdt": 0.002,
           "eth_btc": 0.00016,
           "eos_btc": 0.000004,
           "xrp_btc": 2.4e-7}

# 网格策略eth和btc单量
gap_amount = {"btc_usdt": 30,
              "eth_usdt": 40,
              "eos_usdt": 40,
              "xrp_usdt": 40,
              "eth_btc": 40,
              "eos_btc": 40,
              "xrp_btc": 40}

# 溢价间距
premiumdict = {'elf_usdt': 0.0005, 'doge_usdt': 0.000005, 'btm_usdt': 0.0005, 'bat_usdt': 0.0005,
               'eth3s_usdt': 0.000005, 'btc3s_usdt': 0.000005, 'xmr_usdt': 0.05, 'etc_usdt': 0.0005,
               'hpt_usdt': 0.000005, 'link3l_usdt': 0.0005, 'akro_usdt': 0.00005, 'dot_usdt': 0.0005,
               'act_usdt': 0.000005, 'link_usdt': 0.0005, 'trx_usdt': 0.000005, 'hb10_usdt': 0.0005, 'zec_usdt': 0.05,
               'eth_usdt': 0.05, 'ht_usdt': 0.0005, 'omg_usdt': 0.0005, 'btc_usdt': 0.05, 'iota_usdt': 0.0005,
               'eos_usdt': 0.0005, 'arpa_usdt': 0.000005, 'dash_usdt': 0.05, 'eth3l_usdt': 0.0005, 'bch_usdt': 0.05,
               'iost_usdt': 0.000005, 'atom_usdt': 0.0005, 'rsr_usdt': 0.000005, 'yfii_usdt': 0.0005,
               'bsv_usdt': 0.0005, 'yfi_usdt': 0.05, 'xem_usdt': 0.0005, 'bsv3s_usdt': 0.000005, 'neo_usdt': 0.05,
               'btc3l_usdt': 0.0005, 'bts_usdt': 0.0005, 'xlm_usdt': 0.000005, 'link3s_usdt': 0.000005,
               'ont_usdt': 0.0005, 'xrp_usdt': 0.00005, 'dot2s_usdt': 0.000005, 'uni2l_usdt': 0.0005,
               'ada_usdt': 0.000005, 'fil_usdt': 0.0005, 'uni_usdt': 0.0005, 'dot2l_usdt': 0.0005, 'ae_usdt': 0.0005,
               'ltc_usdt': 0.05, 'uni2s_usdt': 0.000005, 'bhd_usdt': 0.0005, 'bsv3l_usdt': 0.0005}

# 下单价格保留的小数位数(通用，用于定时修改网格间距)
pricelimit0 = {'elf_usdt': 4, 'doge_usdt': 6, 'btm_usdt': 4, 'bat_usdt': 4, 'eth3s_usdt': 6, 'btc3s_usdt': 6,
               'xmr_usdt': 2, 'etc_usdt': 4, 'hpt_usdt': 6, 'link3l_usdt': 4, 'akro_usdt': 5, 'act_usdt': 6,
               'dot_usdt': 4, 'link_usdt': 4, 'trx_usdt': 6, 'hb10_usdt': 4, 'zec_usdt': 2, 'eth_usdt': 2, 'ht_usdt': 4,
               'omg_usdt': 4, 'btc_usdt': 2, 'iota_usdt': 4, 'eos_usdt': 4, 'arpa_usdt': 6, 'dash_usdt': 2,
               'eth3l_usdt': 4, 'bch_usdt': 2, 'iost_usdt': 6, 'atom_usdt': 4, 'rsr_usdt': 6, 'yfii_usdt': 4,
               'bsv_usdt': 4, 'yfi_usdt': 2, 'xem_usdt': 4, 'bsv3s_usdt': 6, 'neo_usdt': 2, 'btc3l_usdt': 4,
               'bts_usdt': 4, 'xlm_usdt': 6, 'link3s_usdt': 6, 'ont_usdt': 4, 'xrp_usdt': 5, 'dot2s_usdt': 6,
               'uni2l_usdt': 4, 'ada_usdt': 6, 'fil_usdt': 4, 'uni_usdt': 4, 'dot2l_usdt': 4, 'ae_usdt': 4,
               'ltc_usdt': 2, 'uni2s_usdt': 6, 'bhd_usdt': 4, 'bsv3l_usdt': 4}

# 下单价格精度限制(即保留几位小数)
pricelimit = {'firo_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'shib_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'ruff_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'em_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'hc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'bsv3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'cspr_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'glm_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'wtc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'xtz_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'dka_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'xmr_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'badger_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'o3_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'algo_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'bcha_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'woo_usdt': {'huobi': 5, 'okex': 5, 'binance': 5, 'befinx': 5},
              'yamv2_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'wicc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'btc3s_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'chr_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'zrx_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'eth3s_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'arpa_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'pha_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'avax_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'pax_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'eth3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'tnb_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'mdx_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'rsr_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'tt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'uma_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'dash_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'xlm_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'sun_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'wnxm_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'hpt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'lamb_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'omg_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'matic_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'front_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'ant_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'bot_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'loom_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'uni_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'crv_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'mx_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'smt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'xem_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'rai_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'eos_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'kava_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'new_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'akro_usdt': {'huobi': 5, 'okex': 5, 'binance': 5, 'befinx': 5},
              'act_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'dht_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'blz_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'waves_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'snt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'btt_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'uni2l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'egt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'dcr_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'vsys_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'xch_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'uip_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'iost_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'itc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'chz_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'insur_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'node_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'cru_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'dac_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'lhb_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'aac_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'soc_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'btm_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'sol_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'mxc_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'stn_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'trx_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'fsn_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'neo_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'xrp_usdt': {'huobi': 5, 'okex': 5, 'binance': 5, 'befinx': 5},
              'qtum_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'fis_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'elf_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'knc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'lba_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'hot_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'theta_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'kan_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'comp_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'cmt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'wbtc_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'kcash_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'hit_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'fil3s_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'ksm_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'bts_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'for_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'lrc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ring_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'lxt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'storj_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'nest_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'yfi_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'mir_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'dot_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'fil_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ar_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'let_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'zec3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'axs_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ogo_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'fti_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'dta_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'forth_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'bal_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ctsi_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'zen_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'nu_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'xmx_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'luna_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'btc1s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'xrt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'zil_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'dock_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'pols_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'eos3s_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'ctxc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'snx_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'atp_usdt': {'huobi': 5, 'okex': 5, 'binance': 5, 'befinx': 5},
              'bags_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'swftc_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'link3s_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'grt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'skm_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'steem_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ankr_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'bsv3s_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'bnt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'zec_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'ekt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'top_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'rndr_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'hive_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'cvc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'bat_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'stake_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'mta_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'lend_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'gt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ach_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'bor_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'lat_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'nkn_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'ren_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'mln_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'cnns_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'pai_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'wxt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'mkr_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'cro_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'mana_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'btc_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'bix_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'nas_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'auction_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'uuu_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'inj_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'hbar_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'waxp_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'apn_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'dot2l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'swrv_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'yam_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'link_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'zec3s_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'mds_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'sand_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'band_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'value_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ocn_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'ltc3s_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'sushi_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'icx_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'utk_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'api3_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'usdc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'seele_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'bch_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'bch3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ela_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'yee_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'ven_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'one_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'icp_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'lol_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'ae_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'enj_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'near_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'xrp3s_usdt': {'huobi': 10, 'okex': 10, 'binance': 10, 'befinx': 10},
              'bch3s_usdt': {'huobi': 8, 'okex': 8, 'binance': 8, 'befinx': 8},
              'reef_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'pearl_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'mco_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'titan_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'aave_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'dai_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'lina_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'uni2s_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'ht_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'link3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ltc3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              '1inch_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'hbc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'bhd_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'skl_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'ont_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'gxc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'oxt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'eos3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'filda_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'rvn_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'beth_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'rlc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'cvp_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ftt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'atom_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'nuls_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'pvt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'stpt_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'flow_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'gnx_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'bsv_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'df_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'zks_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'sc_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'dot2s_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'mask_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'can_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'eth1s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'pond_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'nexo_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'iota_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'vidy_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'iotx_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'trb_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'mass_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'abt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'xrp3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ltc_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'ast_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ogn_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'cre_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'jst_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'iris_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'nano_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'vet_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'btc3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'gof_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'doge_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'nhbtc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'fil3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'ada_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'eth_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
              'ckb_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'etc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'yfii_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
              'nbs_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
              'nsure_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4}}

# 下单数量精度限制
amountlimit = {'firo_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'shib_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'ruff_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'em_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'hc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'bsv3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'cspr_usdt': {'huobi': 1, 'okex': 1, 'binance': 1, 'befinx': 1},
               'glm_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'wtc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'xtz_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'dka_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'xmr_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'badger_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'o3_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'algo_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'bcha_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'woo_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'yamv2_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'wicc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'btc3s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'chr_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'zrx_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'eth3s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'arpa_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'pha_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'avax_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'pax_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'eth3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'tnb_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'mdx_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'rsr_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'tt_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'uma_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'dash_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'xlm_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'sun_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'wnxm_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'hpt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'lamb_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'omg_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'matic_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'front_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ant_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'bot_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
               'loom_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'uni_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'crv_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'mx_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'smt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'xem_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'rai_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'eos_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'kava_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'new_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'akro_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'act_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'dht_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'blz_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'waves_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'snt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'btt_usdt': {'huobi': 0, 'okex': 0, 'binance': 0, 'befinx': 0},
               'uni2l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'egt_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'dcr_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'vsys_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'xch_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'uip_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'iost_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'itc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'chz_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'insur_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'node_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'cru_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'dac_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'lhb_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'aac_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'soc_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'btm_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'sol_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'mxc_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'stn_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'trx_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'fsn_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'neo_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'xrp_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'qtum_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'fis_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'elf_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'knc_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'lba_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'hot_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'theta_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'kan_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'comp_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
               'cmt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'wbtc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'kcash_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'hit_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'fil3s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ksm_usdt': {'huobi': 3, 'okex': 3, 'binance': 3, 'befinx': 3},
               'bts_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'for_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'lrc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ring_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'lxt_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'storj_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'nest_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'yfi_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
               'mir_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'dot_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'fil_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ar_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'let_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'zec3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'axs_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ogo_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'fti_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'dta_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'forth_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'bal_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'ctsi_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'zen_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'nu_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'xmx_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'luna_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'btc1s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'xrt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'zil_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'dock_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'pols_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'eos3s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ctxc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'snx_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'atp_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'bags_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'swftc_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'link3s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'grt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'skm_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'steem_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ankr_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'bsv3s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'bnt_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'zec_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ekt_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'top_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'rndr_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'hive_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'cvc_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'bat_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'stake_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'mta_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'lend_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'gt_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'ach_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'bor_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
               'lat_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'nkn_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'ren_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'mln_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'cnns_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'pai_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'wxt_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'mkr_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
               'cro_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'mana_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'btc_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
               'bix_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'nas_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'auction_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'uuu_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'inj_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'hbar_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'waxp_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'apn_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'dot2l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'swrv_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'yam_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'link_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'zec3s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'mds_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'sand_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'band_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'value_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ocn_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ltc3s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'sushi_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'icx_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'utk_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'api3_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'usdc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'seele_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'bch_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'bch3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ela_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'yee_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'ven_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'one_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'icp_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'lol_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ae_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'enj_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'near_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'xrp3s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'bch3s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'reef_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'pearl_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
               'mco_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'titan_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'aave_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'dai_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'lina_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'uni2s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ht_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'link3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ltc3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               '1inch_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'hbc_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'bhd_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'skl_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ont_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'gxc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'oxt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'eos3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'filda_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'rvn_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'beth_usdt': {'huobi': 6, 'okex': 6, 'binance': 6, 'befinx': 6},
               'rlc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'cvp_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ftt_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'atom_usdt': {'huobi': 3, 'okex': 3, 'binance': 3, 'befinx': 3},
               'nuls_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'pvt_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'stpt_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'flow_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'gnx_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'bsv_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'df_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'zks_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'sc_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'dot2s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'mask_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'can_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'eth1s_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'pond_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'nexo_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'iota_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'vidy_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'iotx_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'trb_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'mass_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'abt_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'xrp3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ltc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ast_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ogn_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'cre_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'jst_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'iris_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'nano_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'vet_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'btc3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'gof_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'doge_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'nhbtc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'fil3l_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ada_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'eth_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'ckb_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'etc_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'yfii_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4},
               'nbs_usdt': {'huobi': 2, 'okex': 2, 'binance': 2, 'befinx': 2},
               'nsure_usdt': {'huobi': 4, 'okex': 4, 'binance': 4, 'befinx': 4}}

# 最小下单量限制
minamountdict = {'firo_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'shib_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'ruff_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'em_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'hc_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'bsv3l_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'cspr_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'glm_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'wtc_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'xtz_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'dka_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'xmr_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'badger_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'o3_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'algo_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'bcha_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'woo_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'yamv2_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'wicc_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'btc3s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'chr_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'zrx_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'eth3s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'arpa_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'pha_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'avax_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'pax_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'eth3l_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'tnb_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'mdx_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'rsr_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'tt_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'uma_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'dash_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'xlm_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'sun_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'wnxm_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'hpt_usdt': {'huobi': 10.0, 'okex': 10.0, 'binance': 10.0, 'befinx': 10.0},
                 'lamb_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'omg_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'matic_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'front_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'ant_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'bot_usdt': {'huobi': 0.00001, 'okex': 0.00001, 'binance': 0.00001, 'befinx': 0.00001},
                 'loom_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'uni_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'crv_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'mx_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'smt_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'xem_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'rai_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'eos_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'kava_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'new_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'akro_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'act_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'dht_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'blz_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'waves_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'snt_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'btt_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'uni2l_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'egt_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'dcr_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'vsys_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'xch_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'uip_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'iost_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'itc_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'chz_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'insur_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'node_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'cru_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'dac_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'lhb_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'aac_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'soc_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'btm_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'sol_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'mxc_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'stn_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'trx_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'fsn_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'neo_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'xrp_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'qtum_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'fis_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'elf_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'knc_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'lba_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'hot_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'theta_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'kan_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'comp_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'cmt_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'wbtc_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'kcash_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'hit_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'fil3s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'ksm_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'bts_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'for_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'lrc_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'ring_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'lxt_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'storj_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'nest_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'yfi_usdt': {'huobi': 0.00001, 'okex': 0.00001, 'binance': 0.00001, 'befinx': 0.00001},
                 'mir_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'dot_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'fil_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'ar_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'let_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'zec3l_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'axs_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'ogo_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'fti_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'dta_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'forth_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'bal_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'ctsi_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'zen_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'nu_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'xmx_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'luna_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'btc1s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'xrt_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'zil_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'dock_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'pols_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'eos3s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'ctxc_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'snx_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'atp_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'bags_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'swftc_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'link3s_usdt': {'huobi': 0.001,
                                 'okex': 0.001,
                                 'binance': 0.001,
                                 'befinx': 0.001},
                 'grt_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'skm_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'steem_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'ankr_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'bsv3s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'bnt_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'zec_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'ekt_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'top_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'rndr_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'hive_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'cvc_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'bat_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'stake_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'mta_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'lend_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'gt_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'ach_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'bor_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'lat_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'nkn_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'ren_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'mln_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'cnns_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'pai_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'wxt_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'mkr_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'cro_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'mana_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'btc_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'bix_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'nas_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'auction_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'uuu_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'inj_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'hbar_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'waxp_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'apn_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'dot2l_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'swrv_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'yam_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'link_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'zec3s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'mds_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'sand_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'band_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'value_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'ocn_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'ltc3s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'sushi_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'icx_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'utk_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'api3_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'usdc_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'seele_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'bch_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'bch3l_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'ela_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'yee_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'ven_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'one_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'icp_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'lol_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'ae_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'enj_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'near_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'xrp3s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'bch3s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'reef_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'pearl_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'mco_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'titan_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'aave_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'dai_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'lina_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'uni2s_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'ht_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'link3l_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'ltc3l_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 '1inch_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'hbc_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'bhd_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'skl_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'ont_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'gxc_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'oxt_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'eos3l_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'filda_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'rvn_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'beth_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'rlc_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'cvp_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'ftt_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'atom_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'nuls_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'pvt_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'stpt_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'flow_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'gnx_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'bsv_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'df_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'zks_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'sc_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'dot2s_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'mask_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'can_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'eth1s_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'pond_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'nexo_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'iota_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'vidy_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'iotx_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'trb_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'mass_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'abt_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'xrp3l_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'ltc_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'ast_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'ogn_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'cre_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'jst_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'iris_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'nano_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'vet_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'btc3l_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'gof_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'doge_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'nhbtc_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'fil3l_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'ada_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'eth_usdt': {'huobi': 0.001, 'okex': 0.001, 'binance': 0.001, 'befinx': 0.001},
                 'ckb_usdt': {'huobi': 1.0, 'okex': 1.0, 'binance': 1.0, 'befinx': 1.0},
                 'etc_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01},
                 'yfii_usdt': {'huobi': 0.0001, 'okex': 0.0001, 'binance': 0.0001, 'befinx': 0.0001},
                 'nbs_usdt': {'huobi': 0.1, 'okex': 0.1, 'binance': 0.1, 'befinx': 0.1},
                 'nsure_usdt': {'huobi': 0.01, 'okex': 0.01, 'binance': 0.01, 'befinx': 0.01}}

symbols = ['firo_usdt', 'ruff_usdt', 'em_usdt', 'hc_usdt', 'glm_usdt', 'wtc_usdt', 'xtz_usdt', 'xmr_usdt',
           'badger_usdt', 'algo_usdt', 'woo_usdt', 'yamv2_usdt', 'wicc_usdt', 'chr_usdt', 'zrx_usdt',
           'arpa_usdt', 'pha_usdt', 'avax_usdt', 'pax_usdt', 'tnb_usdt', 'mdx_usdt', 'lamb_usdt',
           'rsr_usdt', 'tt_usdt', 'uma_usdt', 'dash_usdt', 'xlm_usdt', 'sun_usdt', 'wnxm_usdt', 'hpt_usdt',
           'omg_usdt', 'matic_usdt', 'ant_usdt', 'bot_usdt', 'loom_usdt', 'uni_usdt', 'crv_usdt', 'mx_usdt',
           'xem_usdt', 'eos_usdt', 'kava_usdt', 'new_usdt', 'akro_usdt', 'act_usdt', 'blz_usdt', 'waves_usdt',
           'snt_usdt', 'btt_usdt', 'egt_usdt', 'dcr_usdt', 'vsys_usdt', 'iost_usdt', 'itc_usdt', 'smt_usdt',
           'chz_usdt', 'node_usdt', 'soc_usdt', 'btm_usdt', 'sol_usdt', 'trx_usdt', 'fsn_usdt', 'neo_usdt',
           'qtum_usdt', 'fis_usdt', 'elf_usdt', 'knc_usdt', 'lba_usdt', 'theta_usdt', 'kan_usdt', 'comp_usdt',
           'cmt_usdt', 'hit_usdt', 'ksm_usdt', 'bts_usdt', 'for_usdt', 'lrc_usdt', 'ring_usdt', 'xrp_usdt',
           'storj_usdt', 'nest_usdt', 'yfi_usdt', 'dot_usdt', 'fil_usdt', 'ar_usdt', 'let_usdt', 'cnns_usdt',
           'ogo_usdt', 'dta_usdt', 'bal_usdt', 'zen_usdt', 'luna_usdt', 'btc1s_usdt', 'zil_usdt', 'dock_usdt',
           'pols_usdt', 'ctxc_usdt', 'snx_usdt', 'atp_usdt', 'bags_usdt', 'swftc_usdt', 'inj_usdt', 'beth_usdt',
           'grt_usdt', 'skm_usdt', 'steem_usdt', 'ankr_usdt', 'bnt_usdt', 'zec_usdt', 'top_usdt', 'bsv_usdt',
           'hive_usdt', 'cvc_usdt', 'bat_usdt', 'lend_usdt', 'gt_usdt', 'ach_usdt', 'nkn_usdt', 'mln_usdt',
           'pai_usdt', 'wxt_usdt', 'mkr_usdt', 'cro_usdt', 'mana_usdt', 'btc_usdt', 'bix_usdt', 'nas_usdt',
           'hbar_usdt', 'waxp_usdt', 'link_usdt', 'mds_usdt', 'sand_usdt', 'band_usdt', 'trb_usdt', 'gnx_usdt',
           'ocn_usdt', 'sushi_usdt', 'icx_usdt', 'utk_usdt', 'usdc_usdt', 'bch_usdt', 'ckb_usdt', 'etc_usdt',
           'ela_usdt', 'yee_usdt', 'ven_usdt', 'one_usdt', 'lol_usdt', 'near_usdt', 'yfii_usdt',
           'mco_usdt', 'aave_usdt', 'ht_usdt', '1inch_usdt', 'hbc_usdt', 'nbs_usdt',
           'bhd_usdt', 'skl_usdt', 'ont_usdt', 'gxc_usdt', 'oxt_usdt', 'rvn_usdt', 'iotx_usdt',
           'ftt_usdt', 'atom_usdt', 'nuls_usdt', 'pvt_usdt', 'stpt_usdt', 'flow_usdt', 'jst_usdt',
           'df_usdt', 'eth1s_usdt', 'pond_usdt', 'nexo_usdt', 'iota_usdt', 'vidy_usdt',
           'mass_usdt', 'abt_usdt', 'ltc_usdt', 'ast_usdt', 'ogn_usdt', 'cre_usdt',
           'iris_usdt', 'nano_usdt', 'vet_usdt', 'doge_usdt', 'ada_usdt', 'eth_usdt',
           ]

exchanges = ["okex", "huobi", "binance", "befinx"]

befinx_self_symbol = ["btc_sgdt", "eth_sgdt", "gech_sgdt", "qatc_hjtc"]
